<?php
// productMapping.php

return [
    'mapping' => [
        'palette_660l_papiers' => 'field21',
        'bac_roulant_770l_papiers' => 'field22',
        'benne_10m3_papiers' => 'field23',
        'benne_15m3_papiers' => 'field24',
        'benne_30m3_papiers' => 'field25',
        'palette_660l_cartons' => 'field27',
        'bac_roulant_770l_cartons' => 'field28',
        'benne_10m3_cartons' => 'field29',
        'benne_15m3_cartons' => 'field30',
        'benne_30m3_cartons' => 'field31',
        'palette_660l_plastiques' => 'field33',
        'bac_roulant_770l_plastiques' => 'field34',
        'benne_10m3_plastiques' => 'field35',
        'benne_15m3_plastiques' => 'field36',
        'benne_30m3_plastiques' => 'field37',
        'benne_10m3_palettes' => 'field41',
        'benne_15m3_palettes' => 'field42',
        'benne_30m3_palettes' => 'field43',
        'benne_10m3_encombrants' => 'field47',
        'benne_15m3_encombrants' => 'field48',
        'benne_30m3_encombrants' => 'field49',
        'benne_10m3_dib' => 'field53',
        'benne_15m3_dib' => 'field54',
        'benne_30m3_dib' => 'field55',
        'palette_660l_bois' => 'field57',
        'benne_10m3_bois' => 'field59',
        'benne_15m3_bois' => 'field60',
        'benne_30m3_bois' => 'field61',
        'palette_660l_ferrailles' => 'field63',
        'benne_10m3_ferrailles' => 'field65',
        'benne_15m3_ferrailles' => 'field66',
        'benne_30m3_ferrailles' => 'field67',
        'benne_10m3_dechets_verts' => 'field71',
        'benne_15m3_dechets_verts' => 'field72',
        'benne_30m3_dechets_verts' => 'field73',
        'big_bag_1m3_dib_chantier' => 'field88',
        'benne_chaine_3m3_dib_chantier' => 'field89',
        'benne_chaine_8m3_dib_chantier' => 'field90',
        'benne_chaine_15m3_dib_chantier' => 'field91',
        'benne_ampliroll_30m3_dib_chantier' => 'field93',
        'benne_chaine_8m3_gravats_melange_chantier' => 'field95',
        'big_bag_1m3_gravats_melange_chantier' => 'field96',
        'benne_ampliroll_3m3_gravats_melange_chantier' => 'field97',
        'big_bag_1m3_gravats_propres' => 'field99',
        'benne_ampliroll_3m3_gravats_propres' => 'field100',
        'benne_chaine_8m3_gravats_propres' => 'field101',
        'big_bag_1m3_bois_chantier' => 'field103',
        'benne_ampliroll_3m3_bois_chantier' => 'field104',
        'benne_chaine_8m3_bois_chantier' => 'field105',
        'benne_chaine_15m3_bois_chantier' => 'field106',
        '' => 'field107',
        'benne_ampliroll_30m3_bois_chantier' => 'field108',
        'big_bag_1m3_platre_chantier' => 'field109',
        'benne_chaine_8m3_platre_chantier' => 'field110',
        'box_90L_archives_domicile' => 'field134',
        'box_240L_archives_domicile' => 'field135',
        'box_480L_archives_domicile' => 'field136',
        'benne_8m3_gravats' => 'field157',
        'benne_8m3_dechets' => 'field158',
        'benne_10m3_dechets' => 'field159',
        'benne_15m3_dechets' => 'field160',
        'benne_30m3_dechets' => 'field161',
        'box_d3e_domicile' => 'field178',
        'caisse_palette_domicile' => 'field179',
        'bac_550l_domicile' => 'field180',
        'box_ampoules_domicile' => 'field181',
        'box_neons_domicile' => 'field182',
        'bac_550l_ampoules_domicile' => 'field183',
        'box_cartouche_domicile' => 'field184',
        'bac_550l_cartouche_domicile' => 'field185',
        'bac_pile_6kg_domicile' => 'field186',
        'bac_pile_15kg_domicile' => 'field187',
        'box_90L_archives_depot' => 'field189',
        'box_240L_archives_depot' => 'field190',
        'box_480L_archives_depot' => 'field191',
        'machine_laver_domicile' => 'field192',
        'refrigerateur_domicile' => 'field193',
        'four_domicile' => 'field194',
        'cuisiniere_domicile' => 'field195',
        'box_130L_archives_depot' => 'field196',
        'box_130L_archives_domicile' => 'field197',
        'etage1_avec_ascenseur_camion1' => 'field200',
        'etage1_sans_ascenseur_camion1' => 'field201',
        'etage1_sans_ascenseur_camion1' => 'field202',
        'etage1_sans_ascenseur_camion2' => 'field203',
        'etage1_avec_ascenseur_camion3' => 'field204',
        'etage1_sans_ascenseur_camion3' => 'field205',
        'etage1_avec_ascenseur_camion4' => 'field206',
        'etage1_sans_ascenseur_camion4' => 'field207',
        'etage1_avec_ascenseur_camion5' => 'field208',
        'etage1_sans_ascenseur_camion5' => 'field209',
        'etage1_avec_ascenseur_camion6' => 'field210',
        'etage1_sans_ascenseur_camion6' => 'field211',
        'etage2_avec_ascenseur_camion1' => 'field212',
        'etage2_sans_ascenseur_camion1' => 'field213',
        'etage2_avec_ascenseur_camion2' => 'field214',
        'etage2_sans_ascenseur_camion2' => 'field215',
        'etage2_avec_ascenseur_camion3' => 'field216',
        'etage2_sans_ascenseur_camion3' => 'field217',
        'etage2_avec_ascenseur_camion4' => 'field218',
        'etage2_sans_ascenseur_camion4' => 'field219',
        'etage2_avec_ascenseur_camion5' => 'field220',
        'etage2_sans_ascenseur_camion5' => 'field221',
        'etage2_avec_ascenseur_camion6' => 'field222',
        'etage2_sans_ascenseur_camion6' => 'field223',
        'etage3_avec_ascenseur_camion1' => 'field224',
        'etage3_sans_ascenseur_camion1' => 'field225',
        'etage3_avec_ascenseur_camion2' => 'field226',
        'etage3_sans_ascenseur_camion2' => 'field227',
        'etage3_avec_ascenseur_camion3' => 'field228',
        'etage3_sans_ascenseur_camion3' => 'field229',
        'etage3_avec_ascenseur_camion4' => 'field230',
        'etage3_sans_ascenseur_camion4' => 'field231',
        'etage3_avec_ascenseur_camion5' => 'field232',
        'etage3_sans_ascenseur_camion5' => 'field233',
        'etage3_avec_ascenseur_camion6' => 'field234',
        'etage3_sans_ascenseur_camion6' => 'field235',
        'etage4_avec_ascenseur_camion1' => 'field236',
        'etage4_sans_ascenseur_camion1' => 'field237',
        'etage4_avec_ascenseur_camion2' => 'field238',
        'etage4_sans_ascenseur_camion2' => 'field239',
        'etage4_avec_ascenseur_camion3' => 'field240',
        'etage4_sans_ascenseur_camion3' => 'field241',
        'etage4_avec_ascenseur_camion4' => 'field242',
        'etage4_sans_ascenseur_camion4' => 'field243',
        'etage4_avec_ascenseur_camion5' => 'field244',
        'etage4_sans_ascenseur_camion5' => 'field245',
        'etage4_avec_ascenseur_camion6' => 'field246',
        'etage4_sans_ascenseur_camion6' => 'field247',
        'etage5_avec_ascenseur_camion1' => 'field248',
        'etage5_sans_ascenseur_camion1' => 'field249',
        'etage5_avec_ascenseur_camion2' => 'field250',
        'etage5_sans_ascenseur_camion2' => 'field251',
        'etage5_avec_ascenseur_camion3' => 'field252',
        'etage5_sans_ascenseur_camion3' => 'field253',
        'etage5_avec_ascenseur_camion4' => 'field254',
        'etage5_sans_ascenseur_camion4' => 'field255',
        'etage5_avec_ascenseur_camion5' => 'field256',
        'etage5_sans_ascenseur_camion5' => 'field257',
        'etage5_avec_ascenseur_camion6' => 'field258',
        'etage5_sans_ascenseur_camion6' => 'field259',
        'etage6_avec_ascenseur_camion1' => 'field260',
        'etage6_sans_ascenseur_camion1' => 'field261',
        'etage6_avec_ascenseur_camion2' => 'field262',
        'etage6_sans_ascenseur_camion2' => 'field263',
        'etage6_avec_ascenseur_camion3' => 'field264',
        'etage6_sans_ascenseur_camion3' => 'field265',
        'etage6_avec_ascenseur_camion4' => 'field266',
        'etage6_sans_ascenseur_camion4' => 'field267',
        'etage6_avec_ascenseur_camion5' => 'field268',
        'etage6_sans_ascenseur_camion5' => 'field269',
        'etage6_avec_ascenseur_camion6' => 'field270',
        'etage6_sans_ascenseur_camion6' => 'field271',
        'soussol1_avec_ascenseur_camion1' => 'field272',
        'soussol1_sans_ascenseur_camion1' => 'field273',
        'soussol1_avec_ascenseur_camion2' => 'field274',
        'soussol1_sans_ascenseur_camion2' => 'field275',
        'soussol1_avec_ascenseur_camion3' => 'field276',
        'soussol1_sans_ascenseur_camion3' => 'field277',
        'soussol1_avec_ascenseur_camion4' => 'field278',
        'soussol1_sans_ascenseur_camion4' => 'field279',
        'soussol1_avec_ascenseur_camion5' => 'field280',
        'soussol1_sans_ascenseur_camion5' => 'field281',
        'soussol1_avec_ascenseur_camion6' => 'field282',
        'soussol1_sans_ascenseur_camion6' => 'field283',
        'soussol2_avec_ascenseur_camion1' => 'field284',
        'soussol2_sans_ascenseur_camion1' => 'field285',
        'soussol2_avec_ascenseur_camion2' => 'field286',
        'soussol2_sans_ascenseur_camion2' => 'field287',
        'soussol2_avec_ascenseur_camion3' => 'field288',
        'soussol2_sans_ascenseur_camion3' => 'field289',
        'soussol2_avec_ascenseur_camion4' => 'field290',
        'soussol2_sans_ascenseur_camion4' => 'field291',
        'soussol2_avec_ascenseur_camion5' => 'field292',
        'soussol2_sans_ascenseur_camion5' => 'field293',
        'soussol2_avec_ascenseur_camion6' => 'field294',
        'soussol2_sans_ascenseur_camion6' => 'field295',
        'etageRDC_avec_ascenseur_camion1' => 'field296',
        'etageRDC_sans_ascenseur_camion1' => 'field297',
        'etageRDC_avec_ascenseur_camion2' => 'field298',
        'etageRDC_sans_ascenseur_camion2' => 'field299',
        'etageRDC_avec_ascenseur_camion3' => 'field300',
        'etageRDC_sans_ascenseur_camion3' => 'field301',
        'etageRDC_avec_ascenseur_camion4' => 'field302',
        'etageRDC_sans_ascenseur_camion4' => 'field303',
        'etageRDC_avec_ascenseur_camion5' => 'field304',
        'etageRDC_sans_ascenseur_camion5' => 'field305',
        'etageRDC_avec_ascenseur_camion6' => 'field306',
        'etageRDC_sans_ascenseur_camion6' => 'field307',
        'box_gobelet' => 'field308',
        'box_capsule' => 'field309',
        'box_biodechets_hebdo' => 'field310',
        'box_biodechets_2semaines' => 'field311',
        'box_piles' => 'field312',
        'box_bouteilles_canettes' => 'field313',
        'box_papier' => 'field314',
        'lot_5_box_papier' => 'field315',
        'box_d3e' => 'field316',
        'box_secure_90' => 'field317',
        'box_secure_120' => 'field318',
        'box_secure_240' => 'field319',
        'box_secure_480' => 'field320',
        'vrac_domicile_estimer_archives' => 'field321',
        'vrac_depot_estimer_archives' => 'field322',
        '' => 'field323',
        '' => 'field324',
        '' => 'field325',
        '' => 'field326',
        '' => 'field327',
        'box_gobelet_2' => 'field328',
        'box_gobelet_3' => 'field329',
        'box_gobelet_4' => 'field330',
        'box_gobelet_5' => 'field331',
        'box_gobelet_6' => 'field332',
        'box_capsule_2' => 'field333',
        'box_capsule_3' => 'field334',
        'box_capsule_4' => 'field335',
        'box_capsule_5' => 'field336',
        'box_capsule_6' => 'field337',
        'box_biodechets_hebdo_2' => 'field338',
        'box_biodechets_hebdo_3' => 'field339',
        'box_biodechets_hebdo_4' => 'field340',
        'box_biodechets_hebdo_5' => 'field341',
        'box_biodechets_hebdo_6' => 'field342',
        'box_biodechets_2semaines_2' => 'field343',
        'box_biodechets_2semaines_3' => 'field344',
        'box_biodechets_2semaines_4' => 'field345',
        'box_biodechets_2semaines_5' => 'field346',
        'box_biodechets_2semaines_6' => 'field347',
        'box_piles_2' => 'field348',
        'box_piles_3' => 'field349',
        'box_piles_4' => 'field350',
        'box_piles_5' => 'field351',
        'box_piles_6' => 'field352',
        'box_bouteilles_canettes_2' => 'field353',
        'box_bouteilles_canettes_3' => 'field354',
        'box_bouteilles_canettes_4' => 'field355',
        'box_bouteilles_canettes_5' => 'field356',
        'box_bouteilles_canettes_6' => 'field357',
        'box_papier_2' => 'field358',
        'box_papier_3' => 'field359',
        'box_papier_4' => 'field360',
        'box_papier_5' => 'field361',
        'box_papier_6' => 'field362',
        'lot_5_box_papier_2' => 'field363',
        'lot_5_box_papier_3' => 'field364',
        'lot_5_box_papier_4' => 'field365',
        'lot_5_box_papier_5' => 'field366',
        'lot_5_box_papier_6' => 'field367',
        'box_d3e_bureau_2' => 'field368',
        'box_d3e_bureau_3' => 'field369',
        'box_d3e_bureau_4' => 'field370',
        'box_d3e_bureau_5' => 'field371',
        'box_d3e_bureau_6' => 'field372',
        'box_secure_90_2' => 'field373',
        'box_secure_90_3' => 'field374',
        'box_secure_90_4' => 'field375',
        'box_secure_90_5' => 'field376',
        'box_secure_90_6' => 'field377',
        'box_secure_120_2' => 'field378',
        'box_secure_120_3' => 'field379',
        'box_secure_120_4' => 'field380',
        'box_secure_120_5' => 'field381',
        'box_secure_120_6' => 'field382',
        'box_secure_240_2' => 'field383',
        'box_secure_240_3' => 'field384',
        'box_secure_240_4' => 'field385',
        'box_secure_240_5' => 'field386',
        'box_secure_240_6' => 'field387',
        'box_secure_480_2' => 'field388',
        'box_secure_480_3' => 'field389',
        'box_secure_480_4' => 'field390',
        'box_secure_480_5' => 'field391',
        'box_secure_480_6' => 'field392',
        'box_secure_90_archives' => 'field393',
        'benne_20m3_Dib' => 'field394',
        'benne_20m3_encombrants' => 'field395',
        'benne_20m3_palettes' => 'field396',
        'benne_10m3_platres' => 'field397',
        'box_cartouche_domicile' => 'field398',
        'bac_industriel_200_DEEE_domicile' => 'field399',
        'bac_toner_200l_domicile' => 'field400',
        'bac_200l_ampoules_domicile' => 'field401',
        'bac_secure_240_ouvert_domicile' => 'field402',
        'bac_secure_550_ouvert_domicile' => 'field403',
        'congelateur_domicile' => 'field404',
        'climatisation_domicile' => 'field405',
        'chauffage_domicile ' => 'field406',
        'box_90L_archives_depot_2' => 'field407',
        'box_90L_archives_depot_3' => 'field408',
        'box_90L_archives_depot_4' => 'field409',
        'box_90L_archives_depot_5' => 'field410',
        'box_90L_archives_depot_6' => 'field411',
        'box_130L_archives_depot_2' => 'field412',
        'box_130L_archives_depot_3' => 'field413',
        'box_130L_archives_depot_4' => 'field414',
        'box_130L_archives_depot_5' => 'field415',
        'box_130L_archives_depot_6' => 'field416',
        'bac_secure_240_ouvert_depot_2' => 'field417',
        'bac_secure_240_ouvert_depot_3' => 'field418',
        'bac_secure_240_ouvert_depot_4' => 'field419',
        'bac_secure_240_ouvert_depot_5' => 'field420',
        'bac_secure_240_ouvert_depot_6' => 'field421',
        'box_480L_archives_depot_2' => 'field422',
        'box_480L_archives_depot_3' => 'field423',
        'box_480L_archives_depot_4' => 'field424',
        'box_480L_archives_depot_5' => 'field425',
        'box_480L_archives_depot_6' => 'field426',
        'bac_secure_550_ouvert_depot_2' => 'field427',
        'bac_secure_550_ouvert_depot_3' => 'field428',
        'bac_secure_550_ouvert_depot_4' => 'field429',
        'bac_secure_550_ouvert_depot_5' => 'field430',
        'bac_secure_550_ouvert_depot_6' => 'field431',
        'box_90L_archives_domicile_2' => 'field437',
        'box_90L_archives_domicile_3' => 'field438',
        'box_90L_archives_domicile_4' => 'field439',
        'box_90L_archives_domicile_5' => 'field440',
        'box_90L_archives_domicile_6' => 'field441',
        'box_130L_archives_domicile_2' => 'field442',
        'box_130L_archives_domicile_3' => 'field443',
        'box_130L_archives_domicile_4' => 'field444',
        'box_130L_archives_domicile_5' => 'field445',
        'box_130L_archives_domicile_6' => 'field446',
        'bac_secure_240_ouvert_domicile_2' => 'field447',
        'bac_secure_240_ouvert_domicile_3' => 'field448',
        'bac_secure_240_ouvert_domicile_4' => 'field449',
        'bac_secure_240_ouvert_domicile_5' => 'field450',
        'bac_secure_240_ouvert_domicile_6' => 'field451',
        'box_480L_archives_domicile_2' => 'field452',
        'box_480L_archives_domicile_3' => 'field453',
        'box_480L_archives_domicile_4' => 'field454',
        'box_480L_archives_domicile_5' => 'field455',
        'box_480L_archives_domicile_6' => 'field456',
        'bac_secure_550_ouvert_domicile_2' => 'field457',
        'bac_secure_550_ouvert_domicile_3' => 'field458',
        'bac_secure_550_ouvert_domicile_4' => 'field459',
        'bac_secure_550_ouvert_domicile_5' => 'field460',
        'bac_secure_550_ouvert_domicile_6' => 'field461',
        'box_d3e_domicile_2' => 'field467',
        'box_d3e_domicile_3' => 'field468',
        'box_d3e_domicile_4' => 'field469',
        'box_d3e_domicile_5' => 'field470',
        'box_d3e_domicile_6' => 'field471',
        'bac_550l_domicile_2' => 'field472',
        'bac_550l_domicile_3' => 'field473',
        'bac_550l_domicile_4' => 'field474',
        'bac_550l_domicile_5' => 'field475',
        'bac_550l_domicile_6' => 'field476',
        'caisse_palette_domicile_2' => 'field477',
        'caisse_palette_domicile_3' => 'field478',
        'caisse_palette_domicile_4' => 'field479',
        'caisse_palette_domicile_5' => 'field480',
        'caisse_palette_domicile_6' => 'field481',
        'bac_industriel_200_DEEE_domicile_2' => 'field482',
        'bac_industriel_200_DEEE_domicile_3' => 'field483',
        'bac_industriel_200_DEEE_domicile_4' => 'field484',
        'bac_industriel_200_DEEE_domicile_5' => 'field485',
        'bac_industriel_200_DEEE_domicile_6' => 'field486',
        'box_d3e_depot_2' => 'field487',
        'box_d3e_depot_3' => 'field488',
        'box_d3e_depot_4' => 'field489',
        'box_d3e_depot_5' => 'field490',
        'box_d3e_depot_6' => 'field491',
        'bac_550l_depot_2' => 'field492',
        'bac_550l_depot_3' => 'field493',
        'bac_550l_depot_4' => 'field494',
        'bac_550l_depot_5' => 'field495',
        'bac_550l_depot_6' => 'field496',
        'caisse_palette_depot_2' => 'field497',
        'caisse_palette_depot_3' => 'field498',
        'caisse_palette_depot_4' => 'field499',
        'caisse_palette_depot_5' => 'field500',
        'caisse_palette_depot_6' => 'field501',
        'bac_industriel_200_DEEE_depot_2' => 'field502',
        'bac_industriel_200_DEEE_depot_3' => 'field503',
        'bac_industriel_200_DEEE_depot_4' => 'field504',
        'bac_industriel_200_DEEE_depot_5' => 'field505',
        'bac_industriel_200_DEEE_depot_6' => 'field506',
        'bac_pile_6kg_depot_2' => 'field507',
        'bac_pile_6kg_depot_3' => 'field508',
        'bac_pile_15kg_depot_2' => 'field509',
        'bac_pile_15kg_depot_3' => 'field510',
        'bac_550l_ampoules_depot_2' => 'field511',
        'bac_550l_ampoules_depot_3' => 'field512',
        'box_neons_depot_2' => 'field513',
        'box_neons_depot_3' => 'field514',
        'box_ampoules_depot_2' => 'field515',
        'box_ampoules_depot_3' => 'field516',
        'bac_200l_ampoules_depot_2' => 'field517',
        'bac_200l_ampoules_depot_3' => 'field518',
        'box_cartouche_depot_2' => 'field519',
        'box_cartouche_depot_3' => 'field520',
        'bac_550l_cartouche_depot_2' => 'field521',
        'bac_550l_cartouche_depot_3' => 'field522',
        'bac_toner_200l_depot_2' => 'field523',
        'bac_toner_200l_depot_3' => 'field524',
        'bac_secure_550_ouvert_depot' => 'field525',
        'box_d3e_depot' => 'field526',
        'bac_550l_depot' => 'field527',
        'caisse_palette_depot' => 'field528',
        'bac_industriel_200_DEEE_depot' => 'field529',
        'bac_pile_6kg_depot' => 'field530',
        'bac_pile_15kg_depot' => 'field531',
        'bac_pile_6kg_domicile_2' => 'field532',
        'bac_pile_6kg_domicile_3' => 'field533',
        'bac_pile_15kg_domicile_2' => 'field534',
        'bac_pile_15kg_domicile_3' => 'field535',
        'bac_550l_ampoules_domicile_2' => 'field536',
        'bac_550l_ampoules_domicile_3' => 'field537',
        'box_neons_domicile_2' => 'field538',
        'box_neons_domicile_3' => 'field539',
        'box_ampoules_domicile_2' => 'field540',
        'box_ampoules_domicile_3' => 'field541',
        'bac_200l_ampoules_domicile_2' => 'field542',
        'bac_200l_ampoules_domicile_3' => 'field543',
        'box_cartouche_domicile_2' => 'field544',
        'box_cartouche_domicile_3' => 'field545',
        'bac_550l_cartouche_domicile_2' => 'field546',
        'bac_550l_cartouche_domicile_3' => 'field547',
        'bac_toner_200l_domicile_2' => 'field548',
        'bac_toner_200l_domicile_3' => 'field549',
        'bac_550l_ampoules_depot' => 'field550',
        'box_neons_depot' => 'field551',
        'box_ampoules_depot' => 'field552',
        'bac_200l_ampoules_depot' => 'field553',
        'box_cartouche_depot' => 'field554',
        'bac_550l_cartouche_depot' => 'field555',
        'bac_toner_200l_depot' => 'field556',
        'chauffage_depot' => 'field557',
        'climatisation_depot' => 'field558',
        'congelateur_depot' => 'field559',
        'cuisiniere_depot' => 'field560',
        'four_depot' => 'field561',
        'machine_laver_depot' => 'field562',
        'refrigerateur_depot' => 'field563',
        'bac_secure_240_ouvert_depot' => 'field564',
        'box_240L_archives_domicile_2' => 'field565',
        'box_240L_archives_domicile_3' => 'field566',
        'box_240L_archives_domicile_4' => 'field567',
        'box_240L_archives_domicile_5' => 'field568',
        'box_240L_archives_domicile_6' => 'field569',
        'box_240L_archives_depot_2' => 'field570',
        'box_240L_archives_depot_3' => 'field571',
        'box_240L_archives_depot_4' => 'field572',
        'box_240L_archives_depot_5' => 'field573',
        'box_240L_archives_depot_6' => 'field574',
        'etage1_avec_ascenseur_camion7' => 'field575',
        'etage1_sans_ascenseur_camion7' => 'field576',
        'etage2_avec_ascenseur_camion7' => 'field577',
        'etage2_sans_ascenseur_camion7' => 'field578',
        'etage3_avec_ascenseur_camion7' => 'field579',
        'etage3_sans_ascenseur_camion7' => 'field580',
        'etage4_avec_ascenseur_camion7' => 'field581',
        'etage4_sans_ascenseur_camion7' => 'field582',
        'etage5_avec_ascenseur_camion7' => 'field583',
        'etage5_sans_ascenseur_camion7' => 'field584',
        'etage6_avec_ascenseur_camion7' => 'field585',
        'etage6_sans_ascenseur_camion7' => 'field586',
        'soussol1_avec_ascenseur_camion7' => 'field587',
        'soussol1_sans_ascenseur_camion7' => 'field588',
        'soussol2_avec_ascenseur_camion7' => 'field589',
        'soussol2_sans_ascenseur_camion7' => 'field590',
        'etageRDC_avec_ascenseur_camion7' => 'field591',
        'etageRDC_sans_ascenseur_camion7' => 'field592',
        'etage1_avec_ascenseur_camion8' => 'field593',
        'etage1_sans_ascenseur_camion8' => 'field594',
        'etage2_avec_ascenseur_camion8' => 'field595',
        'etage2_sans_ascenseur_camion8' => 'field596',
        'etage3_avec_ascenseur_camion8' => 'field597',
        'etage3_sans_ascenseur_camion8' => 'field598',
        'etage4_avec_ascenseur_camion8' => 'field599',
        'etage4_sans_ascenseur_camion8' => 'field600',
        'etage5_avec_ascenseur_camion8' => 'field601',
        'etage5_sans_ascenseur_camion8' => 'field602',
        'etage6_avec_ascenseur_camion8' => 'field603',
        'etage6_sans_ascenseur_camion8' => 'field604',
        'soussol1_avec_ascenseur_camion8' => 'field605',
        'soussol1_sans_ascenseur_camion8' => 'field606',
        'soussol2_avec_ascenseur_camion8' => 'field607',
        'soussol2_sans_ascenseur_camion8' => 'field608',
        'etageRDC_avec_ascenseur_camion8' => 'field609',
        'etageRDC_sans_ascenseur_camion8' => 'field610',
        'etage1_avec_ascenseur_camion9' => 'field611',
        'etage1_sans_ascenseur_camion9' => 'field612',
        'etage2_avec_ascenseur_camion9' => 'field613',
        'etage2_sans_ascenseur_camion9' => 'field614',
        'etage3_avec_ascenseur_camion9' => 'field615',
        'etage3_sans_ascenseur_camion9' => 'field616',
        'etage4_avec_ascenseur_camion9' => 'field617',
        'etage4_sans_ascenseur_camion9' => 'field618',
        'etage5_avec_ascenseur_camion9' => 'field619',
        'etage5_sans_ascenseur_camion9' => 'field620',
        'etage6_avec_ascenseur_camion9' => 'field621',
        'etage6_sans_ascenseur_camion9' => 'field622',
        'soussol1_avec_ascenseur_camion9' => 'field623',
        'soussol1_sans_ascenseur_camion9' => 'field624',
        'soussol2_avec_ascenseur_camion9' => 'field625',
        'soussol2_sans_ascenseur_camion9' => 'field626',
        'etageRDC_avec_ascenseur_camion9' => 'field627',
        'etageRDC_sans_ascenseur_camion9' => 'field628',
        'etage1_avec_ascenseur_camion10' => 'field629',
        'etage1_sans_ascenseur_camion10' => 'field630',
        'etage2_avec_ascenseur_camion10' => 'field631',
        'etage2_sans_ascenseur_camion10' => 'field632',
        'etage3_avec_ascenseur_camion10' => 'field633',
        'etage3_sans_ascenseur_camion10' => 'field634',
        'etage4_avec_ascenseur_camion10' => 'field635',
        'etage4_sans_ascenseur_camion10' => 'field636',
        'etage5_avec_ascenseur_camion10' => 'field637',
        'etage5_sans_ascenseur_camion10' => 'field638',
        'etage6_avec_ascenseur_camion10' => 'field639',
        'etage6_sans_ascenseur_camion10' => 'field640',
        'soussol1_avec_ascenseur_camion10' => 'field641',
        'soussol1_sans_ascenseur_camion10' => 'field642',
        'soussol2_avec_ascenseur_camion10' => 'field643',
        'soussol2_sans_ascenseur_camion10' => 'field644',
        'etageRDC_avec_ascenseur_camion10' => 'field645',
        'etageRDC_sans_ascenseur_camion10' => 'field646',
        'etage1_avec_ascenseur_camion11' => 'field647',
        'etage1_sans_ascenseur_camion11' => 'field648',
        'etage2_avec_ascenseur_camion11' => 'field649',
        'etage2_sans_ascenseur_camion11' => 'field650',
        'etage3_avec_ascenseur_camion11' => 'field651',
        'etage3_sans_ascenseur_camion11' => 'field652',
        'etage4_avec_ascenseur_camion11' => 'field653',
        'etage4_sans_ascenseur_camion11' => 'field654',
        'etage5_avec_ascenseur_camion11' => 'field655',
        'etage5_avec_ascenseur_camion11' => 'field656',
        'etage6_avec_ascenseur_camion11' => 'field657',
        'etage6_sans_ascenseur_camion11' => 'field658',
        'soussol1_avec_ascenseur_camion11' => 'field659',
        'soussol1_sans_ascenseur_camion11' => 'field660',
        'soussol2_avec_ascenseur_camion11' => 'field661',
        'soussol2_sans_ascenseur_camion11' => 'field662',
        'etageRDC_avec_ascenseur_camion11' => 'field663',
        'etageRDC_sans_ascenseur_camion11' => 'field664',
        'etage1_avec_ascenseur_camion12' => 'field665',
        'etage1_sans_ascenseur_camion12' => 'field666',
        'etage2_avec_ascenseur_camion12' => 'field667',
        'etage2_sans_ascenseur_camion12' => 'field668',
        'etage3_avec_ascenseur_camion12' => 'field669',
        'etage3_sans_ascenseur_camion12' => 'field670',
        'etage4_avec_ascenseur_camion12' => 'field671',
        'etage4_sans_ascenseur_camion12' => 'field672',
        'etage5_avec_ascenseur_camion12' => 'field673',
        'etage5_avec_ascenseur_camion12' => 'field674',
        'etage6_avec_ascenseur_camion12' => 'field675',
        'etage6_sans_ascenseur_camion12' => 'field676',
        'soussol1_avec_ascenseur_camion12' => 'field677',
        'soussol1_sans_ascenseur_camion12' => 'field678',
        'soussol2_avec_ascenseur_camion12' => 'field679',
        'soussol2_sans_ascenseur_camion12' => 'field680',
        'etageRDC_avec_ascenseur_camion12' => 'field681',
        'etageRDC_sans_ascenseur_camion12' => 'field682',
        'imprimante_petite_domicile' => 'field683',
        'imprimante_petite_depot' => 'field684',
        'imprimante_moyenne_domicile' => 'field685',
        'imprimante_moyenne_depot' => 'field686',
        'imprimante_grande_domicile' => 'field687',
        'imprimante_grande_depot' => 'field688',
        'dechiqueteuse_domicile' => 'field689',
        'dechiqueteuse_depot' => 'field690',
    ],

    'produits_degressifs' => [
        'box_gobelet',
        'box_capsule',
        'box_biodechets_hebdo',
        'box_biodechets_2semaines',
        'box_piles',
        'box_bouteilles_canettes',
        'box_papier',
        'lot_5_box_papier',
        'box_d3e_bureau',
        'box_secure_90',
        'box_secure_120',
        'box_secure_240',
        'box_secure_480',
        'bac_toner_200l_domicile',
        'bac_550l_cartouche_domicile',
        'box_cartouche_domicile',
        'bac_200l_ampoules_domicile',
        'box_ampoules_domicile',
        'box_neons_domicile',
        'bac_550l_ampoules_domicile',
        'bac_pile_15kg_domicile',
        'bac_pile_6kg_domicile',
        'bac_toner_200l_depot',
        'bac_550l_cartouche_depot',
        'box_cartouche_depot',
        'bac_200l_ampoules_depot',
        'box_ampoules_depot',
        'box_neons_depot',
        'bac_550l_ampoules_depot',
        'bac_pile_15kg_depot',
        'bac_pile_6kg_depot',
        'bac_industriel_200_DEEE_depot',
        'caisse_palette_depot',
        'bac_550l_depot',
        'box_d3e_depot',
        'bac_industriel_200_DEEE_domicile',
        'caisse_palette_domicile',
        'bac_550l_domicile',
        'box_d3e_domicile',
        'bac_secure_550_ouvert_domicile',
        'box_secure_480_domicile',
        'bac_secure_240_ouvert_domicile',
        'box_secure_130_domicile',
        'box_secure_90_domicile',
        'bac_secure_550_ouvert_depot',
        'box_secure_480_depot',
        'bac_secure_240_ouvert_depot',
        'box_secure_130_depot',
        'box_secure_90_depot',
        'box_90L_archives_domicile',
        'box_240L_archives_domicile',
        'box_480L_archives_domicile',
        'box_90L_archives_depot',
        'box_240L_archives_depot',
        'box_480L_archives_depot',
        'box_130L_archives_depot',
        'box_130L_archives_domicile',
    ],
];
